import pygame

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

LINE_WIDTH = 2

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_RIGHT_KEY = pygame.K_d
PLAYER_LEFT_KEY = pygame.K_a
PLAYER_FORWARD_KEY = pygame.K_w
PLAYER_BACKWARDS_KEY = pygame.K_s